{
  
  xtype: 'viewport',
  border: 0,
  margin: 0,
  padding: 0,
  style: 'background: #EBEEF2;',
  maintainFlex: true,
  renderTo : Ext.getBody(),
  layout: {
      type: 'fit'
  },
  items: [{
    id: 'Main',
    xtype: 'container',
    layout: {
        type: 'fit'
    },
    items: [{
    xtype: 'container',
    margin: 0,
    minHeight: 300,
    minWidth: 1200,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    items: [{
            xtype: 'container',
            id: 'VALAMI',
            margin: 10,
            layout: {
                align: 'stretch',
                type: 'vbox'
            },
            flex: 1,
            items: [
                {
                    xtype: 'container',
                    height: 100,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #C9DDF6;',
                                    title: 'kérdőívek',
                                    columns: 1,
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'kérdőívek'
                                        }
                                    ]
                                },{
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #C9DDF6;',
                                    title: 'tagok',
                                    columns: 3,
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'tagok listája'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'tagok importálása'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'tagok exportálása'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'szűrők'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'alcsoportok'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'tag kereső'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'felhasználók'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'visszapattanó e-mailek'
                                        }
                                    ]
                                },{
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #C9DDF6;',
                                    title: 'üzenetek',
                                    columns: 3,
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'e-mail - keret'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'e-mail - tartalom'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'e-mail - küldő'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'e-mail - időzítő'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'e-mail - archívum'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'SMS - küldő'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'SMS - időzítő'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'SMS - archívum'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'kampányok'
                                        }
                                    ]
                                },{
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #C9DDF6;',
                                    title: 'statisztikák',
                                    columns: 3,
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'tagok száma'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'új tagok'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'kérdőív statisztika'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'leiratkozott tagok'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'nem hitelesített feliratkozások'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'üzenetek'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'demográfiai'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'átkattintások'
                                        }
                                    ]
                                },{
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #d6e3f2;',
                                    title: 'háttér feladatok',
                                    columns: 1,
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'háttér feladatok'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'live export'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'buttongroup',
                                    height: 90,
                                    style: 'background: #d6e3f2;',
                                    title: 'beállítások',
                                    columns: 2,
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'adatok'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'automatikus e-mailek'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'automatikus weboldalak'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            text: 'figyelmeztető e-mailek'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'adat beállítások'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'adat csoportok'
                                        }
                                    ]
                                }]
                        }]
                    },{
                    xtype: 'container',
                    height: 22,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            style: 'background: #99bce8;',
                            styleHtmlContent: true,
                            items: [
                                {
                                    xtype: 'tbtext',
                                    text: '<a href="#" style="color: #000000;">főoldal</a>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<font style="color: #000000;">&raquo</font>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<a href="#" style="color: #000000;">permission B2C</a>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<font style="color: #000000;">&raquo</font>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<a href="#" style="color: #000000;">kérdőívek</a>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<font style="color: #000000;">&raquo</font>'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: '<font style="color: #000000; font-weight: bold;">Egyperces nyereményjáték 5.</font>'
                                }
                            ]
                        }
                    ]
                },{
                    xtype: 'container',
                    height: 250,
                    layout: {
                        type: 'fit'
                    },
                    flex: 1,
                    items: [
                        {
                            xtype: 'panel',
                            border: 1,
                            layout: {
                                type: 'accordion'
                            },
                            frameHeader: false,
                            items: [
                                {
                                    xtype: 'panel',
                                    style: 'text-align: center;',
                                    styleHtmlContent: true,
                                    collapsed: true,
                                    title: 'CSOPORTOK',
                                    items: [
                                        
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    style: 'text-align: center;',
                                    styleHtmlContent: true,
                                    collapsed: false,
                                    title: 'ADATBÁZISOK',
                                    items: [
                                        
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    style: 'text-align: center;',
                                    styleHtmlContent: true,
                                    collapsed: true,
                                    title: 'FUTÓ FOLYAMATOK&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font style="color: #7F0000;">(17 folyamat)</font>',
                                    items: [
                                        
                                    ]
                                }
                            ]
                        }
                    ]
                }]
                
                
                },{
            xtype: 'container',
            id:'rigthSide',
            autoShow: true,
            margin: '10 10 10 0',
            width: 200,
            layout: {
                align: 'stretch',
                type: 'vbox'
            },
            items: [
                {
                    xtype: 'container',
                    height: 100,
                    id:'rightSideInnerWrapper',
                    style: 'text-align: center;',
                    styleHtmlContent: true,
                    items: [
                        {
                            xtype: 'image',
                            id:'imageHold',
                            margin: '30 auto 0 auto',
                            src: 'http://demo.hirekmedia.hu/maxima/maxima-170x38.png'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    id:'rightSideInnerWrapperDowner',
                    height: 130,
                    layout: {
                        type: 'fit'
                    },
                    margins: '0 0 20 0',
                    items: [
                        {
                            xtype: 'toolbar',
                            vertical: true,
                            items: [
                                {
                                    xtype: 'tbtext',
                                    style: 'background: #C2D8F0;\ntext-align: center;',
                                    text: '<font style="color: #3E6AAA;">felhasználó</font>'
                                },
                                {
                                    xtype: 'splitbutton',
                                    height: 40,
                                    width: 194,
                                    text: 'Tóth Tamás<br /><font style="color: #888888;">(toth.tamas@hirekmedia.hu)</font>'
                                },
                                {
                                    xtype: 'tbtext',
                                    style: 'background: #C2D8F0;\ntext-align: center;',
                                    text: '<font style="color: #3E6AAA;">adminisztrációs felület</font>'
                                },
                                {
                                    xtype: 'splitbutton',
                                    text: 'magyar'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'fit'
                    },
                    flex: 1,
                    items: [
                        {
                            xtype: 'fieldset',
                            style: 'background: #F2E9D8;\n',
                            layout: {
                                type: 'fit'
                            },
                            title: '<b>SÚGÓ</b>'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 28,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    width: 194,
                                    text: 'szerkeszt'
                                }
                            ]
                        }
                    ]
                }
            ]
        }]
}
]
  }]
}
